include:
    - local: /rust.gitlab-ci.yml

docker:
    extends: .docker
    script:
        - docker build -t $CI_REGISTRY_IMAGE:latest -f Dockerfile .
        - docker build -t $CI_REGISTRY_IMAGE:no_std -f Dockerfile . --build-arg PREBUILT_STD=false
        - docker push $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:no_std
    rules:
        -   changes:
                - Dockerfile

build:
    parallel:
        matrix:
            -   CHANNEL: [ stable, beta, nightly ]
                PROFILE: [ debug, release ]
                TARGET: [ x86_64-unknown-linux-musl ]