stages:
    - build

docker:
    image: docker:latest
    stage: build
    services:
        - name: docker:dind
          entrypoint: [ "env", "-u", "DOCKER_HOST" ]
          command: [ "dockerd-entrypoint.sh" ]
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:latest -f Dockerfile .
        - docker push $CI_REGISTRY_IMAGE:latest
